# Generated by Django 4.0.2 on 2023-05-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attack', models.JSONField()),
                ('defence', models.JSONField()),
                ('effects', models.JSONField()),
                ('req', models.JSONField()),
                ('scale', models.JSONField()),
                ('durability', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('attack_types', models.JSONField()),
                ('obtained', models.JSONField()),
                ('aota_only', models.BooleanField()),
            ],
        ),
    ]
